@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

' Сервисы
System_Boundary(s1, "Система компании") {
    System_Boundary(system_user_service, "Сервис пользователей"){
        System(s_user, "Микросервис управления профилями", "Хранит информацию о пользователях, их заказах, избранном и т.д.")
        System(s_autorize, "Микросервис авторизации", "Осуществляет проверку прав пользователя для работы в системе.")
    }
    System_Boundary(system_trade_service, "Сервис товарной системы") {
        System(s_order, "Микросервис заказов", "Обрабатывает создание, изменение и отслеживание заказов.")
        System(s_catalog, "Микросервис товарного каталога", "Управляет товарами, ценами и характеристиками.")
        System(s_payment, "Микросервис оплаты", "Обрабатывает операцию оплаты, формирует необходимые документы.")
    }
    System_Boundary(system_delivery_service, "Сервис доставки") {
        System(s_route, "Микросервис управления маршрутами/логистики", "Обрабатывает создание, изменение маршрутов.")
        System(s_tracking, "Микросервис отслеживания доставки", "Отслеживает пермещение и статус заказа.")
        System(s_interaction, "Микросервис взаимодействия с внешними службами", "Реализует обмен данными о доставках с партнерскими службами.")
        System(s_distributions, "Микросервис распределения заказа","Реализует распределение заказа на поставщика и внутреннюю доставку компании.")
    }
    System_Boundary(system_warehouse_service, "Сервис управления складами") {
        System(s_control, "Микросервис контроля и пермещения запасов", "Реализует работу с запасами склада.")
        System(s_interaction, "Микросервис взаимодействия с внешними службами", "Реализует обмен данными о доставках с партнерскими службами.")
        System(s_inventory, "Микросервис инвентаризации", "Аналитика и формирование отчетности по запасам и складскому оборудованию.")
    }
    System_Boundary(system_finance_service, "Финансовый сервис\бэкофис") {
        System(s_finance, "Микросервис управления финансовыми потоками", "Обрабатывает платежи и хранит информацию о них.")
        System(s_statistics, "Микросервис для сбора статистики и аналитики ", "Мониторинг работы внутренних и сторонних сервисов и формирование отчетности по их деятельности.")
        System(s_reports, "Микросервис оплат", "Создает счета на оплату для поставщиков и оплаты счетов компании.")
        System(s_tasks, "Микросервис административных задач", "Обрабатывает информацию о внутренних задачах компании.")
    }
}

System_Boundary(s2, "Система поставщиков") {
     System_Boundary(system_provider_service, "Сервис по управления поставками")   
}
@enduml