@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

' Определение участников системы
Person(user, "Пользователь", "Пользователь системы")

' Сервисы
System_Boundary(s1, "Система компании") {
    System_Boundary(system_user_service, "Сервис пользователей"){
        System(s_user, "Микросервис управления профилями", "Хранит информацию о пользователях, их заказах, избранном и т.д.")
        System(s_autorize, "Микросервис авторизации", "Осуществляет проверку прав пользователя для работы в системе.")
    }
    System_Boundary(system_trade_service, "Сервис товарной системы") {
        System(s_order, "Микросервис заказов", "Обрабатывает создание, изменение и отслеживание заказов и отслеживает статусы доставки.")
        System(s_catalog, "Микросервис товарного каталога", "Управляет товарами, ценами и характеристиками.")
        System(s_payment, "Микросервис оплаты", "Обрабатывает операцию оплаты, формирует необходимые документы.")
    }
    System_Boundary(system_delivery_service, "Сервис доставки") {
        System(s_route, "Микросервис управления маршрутами/логистики", "Обрабатывает создание, изменение маршрутов, хранит информацию, через кого реализуется доствавка.")
        System(s_tracking, "Микросервис отслеживания доставки", "Отслеживает пермещение и статус заказа.")
        System(s_interaction, "Микросервис взаимодействия с внешними службами", "Реализует обмен данными о доставках с партнерскими службами.")
        System(s_distributions, "Микросервис распределения заказа","Реализует распределение заказа на поставщика и внутреннюю доставку компании.")
    }
    System_Boundary(system_warehouse_service, "Сервис управления складами") {
        System(s_control, "Микросервис контроля и пермещения запасов", "Реализует работу с запасами склада.")
        System(s_interaction, "Микросервис взаимодействия с внешними службами", "Реализует обмен данными о доставках с партнерскими службами.")
        System(s_inventory, "Микросервис инвентаризации", "Аналитика и формирование отчетности по запасам и складскому оборудованию.")
    }
    System_Boundary(system_finance_service, "Финансовый сервис\бэкофис") {
        System(s_finance, "Микросервис управления финансовыми потоками", "Обрабатывает платежи и хранит информацию о них.")
        System(s_statistics, "Микросервис для сбора статистики и аналитики ", "Мониторинг работы внутренних и сторонних сервисов и формирование отчетности по их деятельности.")
        System(s_reports, "Микросервис оплат", "Создает счета на оплату для поставщиков и оплаты счетов компании.")
        System(s_tasks, "Микросервис административных задач", "Обрабатывает информацию о внутренних задачах компании.")
    }
}

System_Boundary(s2, "Система поставщиков") {
     System_Boundary(system_provider_service, "Сервис по управления поставками")   
}

' Связи
Rel(user, s_autorize, "Проходит авторизацию, чтобы получить доступы к профилю и заказам.")
Rel(user, s_catalog, "Ищет товары и проверят их наличие.")
Rel(s_order, s_tracking, "Проверка статуса доставки.")
Rel(s_catalog, s_autorize, "Прохождение авторизации для оформления заказа и добавления товара в избранное.")
Rel(s_autorize, s_user, "При удачной авторизации дайте доступ к профилю пользователя.")
Rel(s_user, s_order, "Оформление заказа.")
Rel(s_order, s_payment, "Оплата заказа и получение информации по её статусу.")
Rel(s_payment, s_finance, "Отправка информации по оплате.")
Rel(s_inventory, s_control, "Получение информации по запасам.")
Rel(s_inventory, s_statistics, "Отправка информации по проведенной инвентаризации.")
Rel(s_catalog, s_control, "Получение информации о наличие товара на складе.")
Rel(s_route, s_tracking, "Запрашивает информацию о местонахождении заказа.")
Rel(s_interaction, s_route, "Передает информацию о заказе и маршруте.")
Rel(s_payment, s_order, "Передает информацию о статусе заказа, для передачи информации на доставку.")
Rel(s_order, s_distributions, "Передает информацию о заказе.")
Rel(s_distributions, s_route, "Передает информацию по внутренней доставке для формирования логистики.")
Rel(s_route, s_statistics, "Передает информацию по доставке для формирования платежныж документов и отчетности по доставке.")
Rel(s_interaction, system_provider_service, "Передает информацию о заказе для реализации доставки.")
Rel(s_order, system_provider_service, "Передает информацию о заказе для реализации сборки заказа и дальнейшей доставки через поставщика.")
Rel(system_provider_service, s_reports, "Передает счета для оплаты.")
Rel(s_reports, system_provider_service, "Передает счета для оплаты.")
Rel(s_reports, s_finance, "Передает информацию о всех проведенных счетах.")
Rel(s_statistics, s_tasks, "Передает информацию для формирования работ, необходимых бизнесу.")

@enduml