@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

' Сервисы
System_Boundary(s1, "Система компании") {
    System(system_user_service, "Сервис пользователей", "Управляет профилями пользователей и авторизацией.")
    System(system_trade_service, "Сервис товарной системы", "Управляет онлайн-продажами, а также поддерживает управление товарами и заказами в оффлайн-гипермаркетах.")
    System(system_order_service, "Сервис заказов", "Обрабатывает создание, изменение и отслеживание заказов.")
    System(system_delivery_service, "Сервис доставки", "Организует доставку товаров, управляет маршрутами, отслеживает посылки.")
    System(system_warehouse_service, "Сервис управления складами", "Управляет складами и товарными запасами.")
    System(system_finance_service, "Финансовый сервис\бэкофис", "Управление финансовыми потоками, расчетами с клиентами и поставщиками. Мониторинг и аналитика, формирование отчетов.")
}

System_Boundary(s2, "Система поставщиков") {
     System(system_provider_service, "Сервис по управления поставками", "Управляет складом поставщика, информацией о товарах, ценах и заказах.")   
}
@enduml