@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

' Сервисы
System_Boundary(s1, "Система компании") {
    System_Boundary(system_user_service, "Сервис пользователей")
    System_Boundary(system_trade_service, "Сервис товарной системы")
    System_Boundary(system_delivery_service, "Сервис доставки")
    System_Boundary(system_warehouse_service, "Сервис управления складами")
    System_Boundary(system_finance_service, "Финансовый сервис\бэкофис")
}

System_Boundary(s2, "Система поставщиков") {
     System_Boundary(system_provider_service, "Сервис по управления поставками")   
}
@enduml