@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

'Элементы диаграммы
Person(user, "Пользователь", "Пользователь системы")
System(s2, "Система поставщиков", "Система компании поставщиков по реализации товаров и доставки.")

System_Boundary(s, "Система компании") {
    System(s1, "Система компании", "Внутренняя система компании по продаже строительных материалов и товаров для дома.")
}

'Связи между элементами диаграммы
Rel(user, s1, "")
Rel(s1, s2, "")
@enduml