@startuml

|Покупатель|
start
:Выбор товара;
:Добавление в корзину;
:Проверка корзины;

if (Пользователь зарегистрирован?) then (Да)
  :Вход в систему;
else (Нет)
  :Регистрация;
endif

:Ввод данных для доставки;

if (Выбор способа доставки) then (Курьером)
  :Указание адреса доставки курьером;
else (Самовывоз)
  :Указание пункта самовывоза;
endif

if (Выбор способа оплаты) then (Карта)
  :Ввод данных карты;
elseif (Электронный кошелек)
  :Выбор способа электронной оплаты;
else (Наличными при получении)
  :Выбор способа платежа;
endif

:Подтверждение заказа;
:Обработка заказа;

if (Товар в наличии?) then (Да)
  :Подтверждение оплаты;
  :Отправка товара;
  :Уведомление клиента;
else (Нет)
  :Сообщение о недостаточности товара;
  stop
endif

if (Оплата успешна?) then (Да)
  :Подтверждение оплаты;
  :Отправка товара;
  :Уведомление клиента;
else (Нет)
  :Сообщение об ошибке оплаты;
  stop
endif

:Получение товара;

stop

@enduml