@startuml

|Сервис счетов|
start
:Получение данных о маршруте (расстояние, время в пути, количество заправок);

if (Есть время в пути?) then (Да)
  :Учет времени в пути для оценки работы водителя;
else (Нет)
  :Расчет времени в пути по средней скорости;
endif

if (Есть количество заправок?) then (Да)
  :Учет заправок на маршруте;
else (Нет)
  :Оценка количества заправок по расстоянию и характеристикам автомобиля;
endif

:Расчет затрат на топливо;
:Оценка времени работы водителя;
:Добавление дополнительных расходов (например, платные дороги, штрафы);

:Итоговые затраты на логистику;

stop

@enduml