@startuml

Пользователь -> Заказ : Создание заказа (выбор продуктов)
Заказ -> Продукты : Запрос списка выбранных продуктов
Продукты -> Заказ : Возврат выбранных продуктов

Заказ -> Запас : Проверка наличия продуктов
Запас -> Склад : Запрос на проверку наличия на складе
Склад -> Запас : Ответ о наличии товаров
Запас -> Заказ : Ответ о наличии

alt Продукты в наличии
  Заказ -> Склад : Резервирование товаров
  Склад -> Заказ : Подтверждение резервирования

  Заказ -> Оплата : Запрос на оплату
  Оплата -> Заказ : Подтверждение успешной оплаты

  Заказ -> Пользователь : Уведомление о завершении заказа
else Продукты отсутствуют
  Запас -> Заказ : Уведомление о недостатке товара
  Заказ -> Пользователь : Уведомление о недоступности товаров
  Пользователь -> Заказ : Запрос на замену товаров
  Заказ -> Каталог : Запрос альтернативных товаров
  Каталог -> Заказ : Возврат списка альтернатив
  Заказ -> Пользователь : Отображение альтернативных товаров для выбора
  Пользователь -> Заказ : Выбор альтернативных товаров
  Заказ -> Запас : Повторная проверка наличия альтернативных товаров
  Запас -> Склад : Запрос на проверку альтернативных товаров
  Склад -> Запас : Ответ о наличии альтернатив
  Запас -> Заказ : Ответ о наличии альтернатив
  Заказ -> Склад : Резервирование альтернативных товаров
  Склад -> Заказ : Подтверждение резервирования альтернативных товаров

  Заказ -> Оплата : Запрос на оплату
  Оплата -> Заказ : Подтверждение успешной оплаты

  Заказ -> Пользователь : Уведомление о завершении заказа
end

@enduml